#!/bin/sh
set -e

do_() {
    do_halogen
    do_tags
}


do_server() {
    python hpg.py
}


do_halogen() {
    cd halogen
    case $1 in
        w)  pulp --before clear -w browserify -O --to ../server/app.js
            ;;
        *)  pulp browserify --optimise --to ../server/app.js
            ;;
    esac
    cd ..
}

do_tags() {
    psc-docs --format ctags halogen/src/**/*.purs > halogen/tags
}

do_ide() {
    cd halogen
    sleep 2 && echo '{"command":"load"}'|psc-ide-client &
    psc-ide-server
    cd ..
}

do_min() {
    do_halogen
    du -h server/app.js
    closure-compiler server/app.js > app.min.js
    mv app.min.js server/app.js
    du -h server/app.js
}

do_dev() {
    systemctl --user stop hpg
    tmux new-window -n dev dostuff halogen w
    tmux split-window dostuff server
    tmux split-window dostuff ide
}
